project_id = "fjzcftyxgiegarwoovau"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.list-users]
verify_jwt = true
